version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: development:1.0.0
    cpus: 0.5
    mem_limit: .5g
    mem_reservation: 128M 
    container_name: selvensi
    volumes:
      - ./src/:/site/src
      - ./package-lock.json:/site/package-lock.json
      - ./package.json:/site/package.json
    ports:
      - "3000:3000"
    environment:
      POSTGRES_DATABASE_URL: postgres://admin:enteradmin_selvensisecret!@#@postgres_testing:5432/primary

  # postgres:
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   container_name: postgres_testing
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: enteradmin_selvensisecret!@#
  #     POSTGRES_DB: primary
  #   depends_on:
  #     - web